config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  root 'statics#top'
  get 'statics/top' => 'statics#top'

  #school  #comment  #replies
  # resources :schools, only: [:index] do
  #   resources :comment, only: [:index, :create, :new, :show, :destroy] do
  #     resources :replies, only: [:index, :create, :new, :show, :destroy]
  #   end
  #   resources :class, only: [:index, :create, :new, :show, :destroy]
  #   resources :evaluation, only: [:index, :create, :new, :show, :destroy]
  # end

  resources :schools, only: [:index] do
    resources :toppages, only: [:index, :show]
  end


  resources :profile, only: [:index, :create, :new, :show] do
    resources :users, only: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    has_many :likes
    has_many :replys
    belongs_to :user  
    belongs_to :school

   end

   #TODO ユーザーでいくかprofileで行くか確認

app/models/country.rb
class Country < ApplicationRecord
    has_many :school
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :profile
    belongs_to :comment
end

app/models/profile.rb
class Profile < ApplicationRecord
    has_many :likes
    has_many :comments
end

app/models/reply.rb
class Reply < ApplicationRecord
    belongs_to :comment
end

#TODO ユーザーでいくかprofileで行くか確認

app/models/school.rb
class School < ApplicationRecord
    has_many :comment
    belongs_to :country
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/class_controller.rb
class ClassController < ApplicationController
    layout "school_layout"
    def index
        @evaluations = Evaluation.where(school_id: params[:school_id])
        @school = School.find(params[:school_id])
        @evaluation = Evaluation.new
    end

    def show
    end

    def create


        @evaluation = Evaluation.new(evaluation_params)
        @evaluation.user_id = current_user.id
        @evaluation.school_id = params[:school_id]

        
        if @evaluation.save
        flash[:success] = "コメントを投稿しました"
        redirect_to action: "index"
        else
        flash[:success] = "投稿できませんでした"
        end
    end

    private
    def evaluation_params
        params.require(:evaluation).permit(:name, :meaningfulness, :ease, :textbook, :test_information, :other_information)
    end

    def destroy
    end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
    layout "school_layout"
    before_action :authenticate_user!
    def index
        @comments = Comment.where(school_id: params[:school_id])
        @comment = Comment.new
        @school = School.find(params[:school_id])
    end
    def show
        @comment = Comment.find(params[:id])
        @replies = Reply.where(comment_id: params[:comment_id])
        
        # here(comment_id: params[:id])
    end
    # def new
    #     @comment = Comment.new
    #     redirect_to action: "index"
    # end

#追加箇所
    def create
        @comment = Comment.new(comment_params)
        @comment.user_id = current_user.id
        @comment.school_id = params[:school_id]

        
        if @comment.save
        flash[:success] = "コメントを投稿しました"
        redirect_to action: "index"
        else
        flash[:success] = "投稿できませんでした"
        end
    end

    private
    def comment_params
        params.require(:comment).permit(:body)
    end

end

app/controllers/school_controller.rb
class SchoolController < ApplicationController
    
    def index
        @schools = School.all
        @countries = Country.all
    end

    def show
        
        @school = School.find(params[:id])
        render :layout => "school_layout"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_helper.rb
module ClassHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/school_helper.rb
module SchoolHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kgbfkh</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700|Noto+Sans+JP:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


  </head>





  <header>
  <%= link_to statics_top_path do %>
  <%= image_tag 'logo.png', :size =>'30x30' %>
  <% end %>
  <%= link_to '学校を探す', school_index_path %>
  <%= link_to '管理人の部屋',statics_top_path %>
  <%= link_to '問い合わせ', statics_top_path %>
  
  <% if user_signed_in? %>
    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
    <%= link_to '登録情報の修正', edit_user_registration_path %>
    <%= link_to 'プロフィール', profile_path(id: current_user.id) %>
    <% else %>
      <%= link_to '新規登録', new_user_registration_path %>
      <%= link_to 'ログイン', new_user_session_path %>
  <% end %>

  <%= link_to '検索', statics_top_path %>
  <%# <%= form_tag class: 'seartch_form', method: :get do %>
  <%#<%= text_field :book,:isbn,size:20 %>
  <%#<%= submit_tag '検索する' %>
  <%#<% end %>

  </header>
  <body>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/schools_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kgbfkh</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700|Noto+Sans+JP:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <header>
  <%= link_to statics_top_path do %>
  <%= image_tag 'logo.png', :size =>'30x30' %>
  <% end %>
  <%= link_to '学校を探す', schools_path %>
  <%= link_to '管理人の部屋',statics_top_path %>
  <%= link_to '問い合わせ', statics_top_path %>
  <% if user_signed_in? %>
    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
    <%= link_to '登録情報の修正', edit_user_registration_path %>
    <%= link_to 'プロフィール', profile_path(id: current_user.id) %>
    <% else %>
      <%= link_to '新規登録', new_user_registration_path %>
      <%= link_to 'ログイン', new_user_session_path %>
  <% end %>

  <%= link_to '検索', statics_top_path %>
  <%= link_to '#school_layout', statics_top_path %>
  </header>

  <body>
  <div class="container">
  <div class="row">
    <div id="contents">
      <h1><%= @school.name %></h1>
      <ul class="school-function">
        <li　class="btn-top-radius"><%= link_to 'TOP', school_path(id: params[:id]) %></li>
        <li　class="btn-top-radius"><%= link_to '掲示板', school_comment_index_path(school_id: params[:id]) %></li>
        <li　class="btn-top-radius"><%= link_to '授業', school_class_index_path(school_id: params[:id]) %></li>
      </ul>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <div class="left-colum">

<div class="login-block">
    <h3>#school_layout</h3>
    <h3>ログイン/会員登録</h3>
    <p>留学生向けの総合サイトです！</p>
    <p>よかったら登録してって掲示板とか見てみてね〜</p>
</div>

<div class="ad-block">
    <h1>広告</h1>
</div>

<div class="histry-block">
    <h3>閲覧履歴</h3>
    <ul>
    <li><p>アメリカのご飯はおいしくない？！</p></li>
    <li><p>留学の手続きを自分でしてみよう！</p></li>
</div>

<div class="recommend-block">
    <h3>オススメ記事はこちら</h3>
    <ul>
    <li><p>留学#とは</p></li>
    <li><p>管理人オススメの留学エージェント</p></li>
</div>
</div>
  </body>
</html>